### ISSUE TITLE
the installation instructions are broken

### ISSUE THREAD

**Issue by volviq** [grschafer/quassel-search-go#1]
The suggested link for http://www.ansibleworks.com/ leads to a Japanese page about nurseries.
Please update the documentation or make clear that the project has been abandoned and needs rework.

**Comment by grschafer** [comment]
Updated the ansible link. I'm still running an instance of this on a VPS, but I haven't gone through the installation in several years, so I can't promise the same packages exist or that the vagrant/ansible directives still work if you use the latest versions of those tools.

Feel free to reopen this issue if you try installing again and hit other problems.
